mysite/hospitalRanking/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views

app_name = 'hospitalRanking'

urlpatterns = [
    # .com/hospitalRanking/
    url(r'^$', TemplateView.as_view(template_name='hospitalRanking/index.html'), name='index'),
    # .com/hospitalRanking/submitRankingForm
    url(r'^submitRankingForm', views.submit_ranking_form, name='submit_ranking_form'),
    # .com/hospitalRanking/results
    url(r'^results', TemplateView.as_view(template_name='hospitalRanking/results.html'), name='results'),
    # .com/hospitalRanking/hospital/
    url(r'^hospital/(?P<hospital_id>[\w+0-9+]+)/$', views.get_hospital, name='getHospital'),
]

mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    # .com/        --> Index drop page
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),
    # .com/hospitalRanking
    url(r'^hospitalRanking/', include('hospitalRanking.urls')),
    # .com/admin   --> Admin Interface
    url(r'^admin/', admin.site.urls),
]

mysite/hospitalRanking/models.py
from __future__ import unicode_literals
from django.db import models
import json
from random import *
from pprint import pprint
import sys

'''
    A map to easily get/change values of priorities
    Example Access:
        priorityMap['Low'] => .75
        priorityMap['Medium'] => 1.0
        priorityMap['High'] => 1.25
'''
priorityMap = {
    'Low': .75,
    'Medium': 1,
    'High': 1.25,
}


class RankingForm:
    location = ""
    cost_of_care = 0
    timely_effective_care = 0
    complications_and_deaths = 0
    hospital_returns = 0
    doctor_ranking = 0


'''
    The hospital ranking algorithm
'''
class HospitalRankingAlgorithm:
    ranking_form = {}

    def __init__(self, ranking_form):
        self.ranking_form = ranking_form
    
    '''
        Using the filters (Low = .75, Med = 1, High = 1.25) weight the 
        given metrics to create a weighted sum.

        Using that weighted sum, order the hospital list by it from [highest, ..., lowest] 
    '''
    def rank_hospitals_by_filters(self):

        # All hospitals in NC
        hospitals_nc = []

        if self.ranking_form.location != "":
            hospitals_nc = Hospital.objects.filter(state='NC', city__iexact=self.ranking_form.location)
        else:
            hospitals_nc = Hospital.objects.filter(state='NC').all()

        # Setup ranking dictionary
        ranking_dict = dict()
        for hospital in hospitals_nc:
            ranking_dict[hospital.provider_id] = {
                "provider_id": hospital.provider_id,
                "name": hospital.hospital_name,
                "score": 0,
                "address": hospital.address,
                "city": hospital.city,
                "state": hospital.state,
                "zip_code": hospital.zip_code,
                "county_name": hospital.county_name,
                "phone_number": hospital.phone_number,
                "n_payment": 0,
                "n_md": 0,
                "n_timely": 0,
                "n_complications": 0,
                "n_returns": 0
            }

        # Run algorithm per hospital
        for current_hospital in hospitals_nc:
            '''
            Run algorithm and set score(s)
            '''

        # Save dict items into an array that is sorted by item.score
        # Sort by putting [ Higher Scores, ..., Lower Scores ]

        # print self.filters['Complications and Death']
        # 'Complications and Death': '1',
        #  'Doctor Ranking': '1',
        #  'Timely and Effective Care': '1',
        #  'Cost of Care': '1',
        #  'Hospital Returns': '1'

        hospitals_payment = self.payment_rank(hospitals_nc)
        for hsp in hospitals_payment:
            ranking_dict[hsp[0]]['score'] += (float(hsp[1])*float(self.ranking_form.cost_of_care))
            ranking_dict[hsp[0]]['n_payment'] = float(hsp[1])

        hospitals_md = self.md_rank(hospitals_nc)
        for hsp in hospitals_md:
            ranking_dict[hsp[0]]['score'] += (float(hsp[1])*float(self.ranking_form.doctor_ranking))
            ranking_dict[hsp[0]]['n_md'] = float(hsp[1])

        hospitals_timely = self.timely_rank(hospitals_nc)
        for hsp in hospitals_timely:
            ranking_dict[hsp[0]]['score'] += (float(hsp[1])*float(self.ranking_form.timely_effective_care))
            ranking_dict[hsp[0]]['n_timely'] = float(hsp[1])

        hospitals_complications = self.complications_rank(hospitals_nc)
        for hsp in hospitals_complications:
            ranking_dict[hsp[0]]['score'] += (float(hsp[1])*float(self.ranking_form.complications_and_deaths))
            ranking_dict[hsp[0]]['n_complications'] = float(hsp[1])

        hospitals_returns = self.returns_rank(hospitals_nc)
        for hsp in hospitals_returns:
            ranking_dict[hsp[0]]['score'] += (float(hsp[1])*float(self.ranking_form.hospital_returns))
            ranking_dict[hsp[0]]['n_returns'] = float(hsp[1])

        #pprint(ranking_dict)

        # Normalize final results for display 0-1, higher score is better
        max_score = (-1*sys.maxsize) - 1
        min_score = sys.maxsize
        for key in ranking_dict.keys():
            if max_score < ranking_dict[key]['score']:
                max_score = ranking_dict[key]['score']
            if min_score > ranking_dict[key]['score']:
                min_score = ranking_dict[key]['score']

        score_range = max_score - min_score
        for key in ranking_dict.keys():
            if score_range > 0:
                ranking_dict[key]['score'] = (ranking_dict[key]['score'] - min_score) / score_range
            else:
                ranking_dict[key]['score'] = 1

        # End Normalization

        ranked_list = list()
        for key, value in ranking_dict.items():
            ranked_list.append(value)

        # Return the ranked list
        ranked_list.sort(key=lambda item: item['score'], reverse=True)
        return ranked_list

    def payment_rank(self, hospitals_nc):
        # dict use to sort
        hospitals_rating_dict = dict()

        for current_hospital in hospitals_nc:

            # all payment_measurements for given provider_id
            payment_measurements = Normalized_Payment.objects.filter(
                provider_id=current_hospital.provider_id)
            n_score_sum = 0
            n_score_count = 0
            for measurement in payment_measurements:
                # convert $xx,xxx string to int

                n_score_sum += measurement.n_score
                n_score_count += 1

                hospitals_rating_dict[current_hospital.provider_id] = n_score_sum / n_score_count

        # Sort
        # hospitals_rating_dict_sorted = sorted(hospitals_rating_dict.iteritems(), key=lambda d: d[1])
        return hospitals_rating_dict.items()

    def md_rank(self, hospitals_nc):
        # dict use to sort
        hospitals_rating_dict = dict()

        for current_hospital in hospitals_nc:

            # all payment_measurements for given provider_id
            md_score = MD_Score.objects.filter(
                provider_id=current_hospital.provider_id)
            n_score_sum = 0
            n_score_count = 0
            for score in md_score:
                # convert $xx,xxx string to int

                n_score_sum += score.score
                n_score_count += 1

                hospitals_rating_dict[current_hospital.provider_id] = n_score_sum / n_score_count

        # Sort
        # hospitals_rating_dict_sorted = sorted(hospitals_rating_dict.iteritems(), key=lambda d: d[1])
        return hospitals_rating_dict.items()


    def timely_rank(self, hospitals_nc):
        # dict use to sort
        hospitals_rating_dict = dict()

        for current_hospital in hospitals_nc:

            # all payment_measurements for given provider_id
            payment_measurements = Normalized_Timely.objects.filter(
                provider_id=current_hospital.provider_id)
            n_score_sum = 0
            n_score_count = 0
            for measurement in payment_measurements:
                # convert $xx,xxx string to int

                n_score_sum += measurement.n_score
                n_score_count += 1

                hospitals_rating_dict[current_hospital.provider_id] = n_score_sum / n_score_count

        # Sort
        # hospitals_rating_dict_sorted = sorted(hospitals_rating_dict.iteritems(), key=lambda d: d[1])
        return hospitals_rating_dict.items()

    def complications_rank(self, hospitals_nc):
        # dict use to sort
        hospitals_rating_dict = dict()

        for current_hospital in hospitals_nc:

            # all payment_measurements for given provider_id
            payment_measurements = Normalized_Complications.objects.filter(
                provider_id=current_hospital.provider_id)
            n_score_sum = 0
            n_score_count = 0
            for measurement in payment_measurements:
                # convert $xx,xxx string to int

                n_score_sum += measurement.n_score
                n_score_count += 1

                hospitals_rating_dict[current_hospital.provider_id] = n_score_sum / n_score_count

        # Sort
        # hospitals_rating_dict_sorted = sorted(hospitals_rating_dict.iteritems(), key=lambda d: d[1])
        return hospitals_rating_dict.items()

    def returns_rank(self, hospitals_nc):
        # dict use to sort
        hospitals_rating_dict = dict()

        for current_hospital in hospitals_nc:

            # all payment_measurements for given provider_id
            payment_measurements = Normalized_Returns.objects.filter(
                provider_id=current_hospital.provider_id)
            n_score_sum = 0
            n_score_count = 0
            for measurement in payment_measurements:
                # convert $xx,xxx string to int

                n_score_sum += measurement.n_score
                n_score_count += 1

                hospitals_rating_dict[current_hospital.provider_id] = n_score_sum / n_score_count

        # Sort
        # hospitals_rating_dict_sorted = sorted(hospitals_rating_dict.iteritems(), key=lambda d: d[1])
        return hospitals_rating_dict.items()


class Footnotes(models.Model):
    footnote = models.CharField(primary_key=True, max_length=6)
    footnote_text = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'Footnotes'


class Hospital(models.Model):
    provider_id = models.IntegerField(primary_key=True)
    hospital_name = models.CharField(max_length=50, blank=True, null=True)
    address = models.CharField(max_length=50, blank=True, null=True)
    city = models.CharField(max_length=50, blank=True, null=True)
    state = models.CharField(max_length=2)
    zip_code = models.IntegerField(blank=True, null=True)
    county_name = models.CharField(max_length=50, blank=True, null=True)
    phone_number = models.IntegerField(blank=True, null=True)
    hospital_type = models.CharField(max_length=50, blank=True, null=True)

mysite/hospitalRanking/views.py
from django.conf import settings
from django.shortcuts import render, redirect
from django.http import Http404, JsonResponse
from . models import HospitalRankingAlgorithm, Hospital, RankingForm
from pprint import pprint
import json


# Create your views here.
def submit_ranking_form(request):
    if request.method == 'POST':

        # Example of how to get the form values
        ranking_form = RankingForm()
        ranking_form.location = request.POST['location']
        ranking_form.cost_of_care = request.POST['CostOfCare']
        ranking_form.timely_effective_care = request.POST['TimelyEffectiveCare']
        ranking_form.complications_and_deaths = request.POST['ComplicationsAndDeaths']
        ranking_form.hospital_returns = request.POST['HospitalReturns']
        ranking_form.doctor_ranking = request.POST['DoctorRank']

        context = {
            'location_options': {
                'Location': str(ranking_form.location),
            },
            'priorities': {
                'Cost of Care': str(ranking_form.cost_of_care),
                'Timely and Effective Care': str(ranking_form.timely_effective_care),
                'Complications and Death': str(ranking_form.complications_and_deaths),
                'Hospital Returns': str(ranking_form.hospital_returns),
                'Doctor Ranking': str(ranking_form.doctor_ranking)
            },
            'hospitals': []
        }

        # Create algorithm, run it, save it
        ranked_hospitals = HospitalRankingAlgorithm(ranking_form).rank_hospitals_by_filters()
        #pprint(ranked_hospitals)
        context['hospitals'] = ranked_hospitals

        # Print context
        #print(str(json.dumps(context, indent=4, sort_keys=True)))

        return render(request, 'hospitalRanking/results.html', {'context': context})
    else:
        raise Http404("Invalid request")


def get_hospital(request, hospital_id):
    hospitals = Hospital.objects.filter(provider_id=hospital_id)
    if hospitals.exists():
        context = {
            'hospital': hospitals[0]
        }
        return render(request, 'hospitalRanking/hospital.html', context)
    else:
        raise Http404("Invalid request")

mysite/hospitalRanking/templates/hospitalRanking/hospital.html
{% extends 'base.html' %}
{% block title %}Hospital Ranking Form{% endblock %}

<head>
    {% load staticfiles %}
    {% load hospitalRanking_extras %}
</head>


{% block body %}
<div class="container">

    <div class="page-header text-center">
        <h2>Hospital Info</h2>
    </div>

    <div class="panel panel-primary">
        <div class="panel-heading text-center">
            <h3 class="panel-title"><strong>{{ hospital.hospital_name }}</strong></h3>
        </div>
        <div class="panel-body">
            <div class="row">
                <h4 class="text-center">Contact Information</h4>
                <div class="col-sm-6">
                    <h4 class="text-center">Address</h4>
                    <div class="col-sm-offset-4">
                        <p>{{ hospital.address }}</p>
                        <p>{{ hospital.city }}, {{ hospital.state }} {{ hospital.zip_code }}</p>
                        <p><label>County</label> : {{ hospital.county_name }}</p>

                    </div>
                </div>
                <div class="col-sm-6">
                    <h4 class="text-center">Phone Info</h4>
                    <div class="col-sm-offset-4">
                        <p>{{ hospital.phone_number | phonenumber }}</p>
                    </div>
                </div>
            </div>
            <hr />

            <div class="row">

            </div>
        </div>
    </div>
</div>

<script src="{% static 'hospitalRanking/js/index.js' %}"></script>
{% endblock %}

mysite/hospitalRanking/templates/hospitalRanking/index.html
{% extends 'base.html' %}
{% block title %}Hospital Ranking Form{% endblock %}

<head>
    {% load staticfiles %}
</head>


{% block body %}
<div class="container">
    <div class="well text-center">
        <p>Please fill out the form with your rankings so that we can customize the results to your needs.</p>
    </div>

    <div class="panel panel-primary">
        <div class="panel-heading text-center">
            <h3 class="panel-title">Hospital Ranking Form</h3>
        </div>
        <div class="panel-body">
            <form id="rankingForm" class="form-horizontal" method="post" action="{% url 'hospitalRanking:submit_ranking_form' %}">
                {% csrf_token %}
                <h4 class="text-center">Location</h4>
                <div class="row">
                    <div class="col-sm-offset-3 col-sm-6">
                        <label for="location" class="col-sm-4 control-label">City <small>(Optional)</small></label>
                        <div class="col-sm-8">
                            <input id="location" class="form-control" name="location" placeholder="Raleigh">
                        </div>
                    </div>
                </div>

                <hr>

                <h4 class="text-center">Priorities</h4>
                <div class="row" style="padding: 1em;">
                    <div class="col-sm-offset-1 col-sm-5">
                        <div class="form-group">
                            <label for="CostOfCare" class="col-sm-4 control-label">Cost of Care</label>
                            <div class="col-sm-8">
                                <input
                                    id="CostOfCare" class="form-control" type="text" name="CostOfCare"
                                    data-provide="slider"
                                    data-slider-min="0"
                                    data-slider-max="1"
                                    data-slider-step="0.05"
                                    data-slider-value="0.5"
                                    data-slider-ticks="[0, 0.5, 1.0]"
                                    data-slider-ticks-labels='["Low", "Medium", "High"]'>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-5">
                        <div class="form-group">
                            <label for="TimelyEffectiveCare" class="col-sm-4 control-label">Timely and Effective Care</label>
                            <div class="col-sm-8">
                                <input
                                    id="TimelyEffectiveCare" class="form-control" type="text" name="TimelyEffectiveCare"
                                    data-provide="slider"
                                    data-slider-min="0"
                                    data-slider-max="1"
                                    data-slider-step="0.05"
                                    data-slider-value="0.5"
                                    data-slider-ticks="[0, 0.5, 1.0]"
                                    data-slider-ticks-labels='["Low", "Medium", "High"]'>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row" style="padding: 1em;">
                    <div class="col-sm-offset-1 col-sm-5">
                        <div class="form-group">
                            <label for="ComplicationsAndDeaths" class="col-sm-4 control-label">Complications and Deaths</label>
                            <div class="col-sm-8">
                                <input
                                    id="ComplicationsAndDeaths" class="form-control" type="text" name="ComplicationsAndDeaths"
                                    data-provide="slider"
                                    data-slider-min="0"
                                    data-slider-max="1"
                                    data-slider-step="0.05"
                                    data-slider-value="0.5"
                                    data-slider-ticks="[0, 0.5, 1.0]"
                                    data-slider-ticks-labels='["Low", "Medium", "High"]'>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-5">
                        <div class="form-group">
                            <label for="HospitalReturns" class="col-sm-4 control-label">Hospital Returns</label>
                            <div class="col-sm-8">
                                <input
                                    id="HospitalReturns" class="form-control" type="text" name="HospitalReturns"
                                    data-provide="slider"
                                    data-slider-min="0"
                                    data-slider-max="1"
                                    data-slider-step="0.05"
                                    data-slider-value="0.5"
                                    data-slider-ticks="[0, 0.5, 1.0]"
                                    data-slider-ticks-labels='["Low", "Medium", "High"]'>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row" style="padding: 1em;">
                    <div class="col-sm-offset-1 col-sm-5">
                        <div class="form-group">
                            <label for="DoctorRank" class="col-sm-4 control-label">Doctor Rank</label>
                            <div class="col-sm-8">
                                <input
                                    id="DoctorRank" class="form-control" type="text" name="DoctorRank"
                                    data-provide="slider"
                                    data-slider-min="0"
                                    data-slider-max="1"
                                    data-slider-step="0.05"
                                    data-slider-value="0.5"
                                    data-slider-ticks="[0, 0.5, 1.0]"
                                    data-slider-ticks-labels='["Low", "Medium", "High"]'>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="text-center">
                    <button id="submitButton" type="submit" class="btn btn-primary">Submit</button>
                    <button id="resetButton" type="button" class="btn btn-secondary">Reset</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script src="{% static 'hospitalRanking/js/index.js' %}"></script>
<script>

</script>
{% endblock %}

mysite/hospitalRanking/templates/hospitalRanking/results.html
{% extends 'base.html' %}

{% block title %}Hospital Ranking Results{% endblock %}

<head>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'hospitalRanking/css/results.css' %}"/>
</head>

{% block body %}
<div class="container">

    <div class="page-header text-center">
        <h2>Hospital Ranking Results</h2>
        <h4>Need to make another search? Click <a href="{% url 'hospitalRanking:index' %}"> here</a>.</h4>
    </div>


    <div class="panel panel-primary">
        <div class="panel-heading">
            <button type="button" class="btn btn-sm btn-info" data-toggle="collapse" href="#collapsablePanel">Show/Hide Form</button>
            <h3 class="panel-title text-center">Hospital Ranking Submitted Form</h3>
        </div>
        <div id="collapsablePanel" class="panel-collapse">
            <div class="panel-body">
                <!-- This just prints the dictionary we pass here -->
                <form id="form-body" class="form-horizontal">
                    <div class="row">
                        <h4 class="text-center">Location</h4>
                        <div class="col-sm-offset-3 col-sm-6">
                            <label for="location" class="col-sm-4 control-label">City</label>
                            <div class="col-sm-8">
                                <input id="location" class="form-control" name="location" value="{{ context.location_options.Location }}" disabled>
                            </div>
                        </div>
                    </div>

                    <hr>

                    <div class="row">
                        <h4 class="text-center">Priorities</h4>
                        {% for key,value in context.priorities.items %}
                            <div class="col-sm-6">
                                <div class="form-group">

                                    <label for="CostOfCare" class="col-sm-4 control-label">{{ key }}</label>
                                    <div class="col-sm-8">
                                        <input id="CostOfCare" class="form-control" type="text" name="CostOfCare"
                                            data-provide="slider"
                                            data-slider-min="0"
                                            data-slider-max="1"
                                            data-slider-step="0.05"
                                            data-slider-value="0.5"
                                            data-slider-ticks="[0, 0.5, 1.0]"
                                            data-slider-ticks-labels='["Low", "Medium", "High"]'
                                            data-slider-enabled="false">
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="panel panel-primary">
        <div class="panel-heading text-center">
            <h3 class="panel-title">Ranked Hospitals</h3>
            <h6><i>Hospitals are ranked relative to each other.</i></h6>
        </div>
        <div class="panel-body">
            <div class="row">
                <div id="loadingWrapper">
                    <h3  class="text-center">
                        <i class="fa fa-circle-o-notch fa-spin" style="font-size: 36px"></i> Loading
                    </h3>
                    <br />
                </div>

                <div id="hospitalsTableWrapper" class="col-sm-12">
                    <table class="table table-striped baseDataTable">
                        <thead>
                            <tr>
                                <th class="text-center"> Hospital</th>
                                <th class="text-center">Overall</th>
                                <th class="text-center">Payment</th>
                                <th class="text-center">Doctors</th>
                                <th class="text-center">Complications</th>
                                <th class="text-center">Returns</th>
                                <th class="text-center">Timely</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for hospital in context.hospitals %}
                        <tr>
                            <td><a href="hospital/{{ hospital.provider_id }}">{{ hospital.name | title }}</a></td>
                            <td><div id="overallScore-{{ hospital.provider_id }}" style="height: 50px;"></div></td>
                            <td><div id="payment-{{ hospital.provider_id }}" style="height: 50px;"></div></td>
                            <td><div id="doctors-{{ hospital.provider_id }}" style="height: 50px;"></div></td>
                            <td><div id="complications-{{ hospital.provider_id }}" style="height: 50px;"></div></td>
                            <td><div id="returns-{{ hospital.provider_id }}" style="height: 50px;"></div></td>
                            <td><div id="timely-{{ hospital.provider_id }}" style="height: 50px;"></div></td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>


</div>

<script src="{% static 'hospitalRanking/js/results.js' %}"></script>
<script>
$(function () {
    $("#collapsablePanel").addClass("collapse");
    $("#hospitalsTableWrapper").hide();
    
    {% for hospital in context.hospitals %}
        createCircleProgressBar("#overallScore-{{ hospital.provider_id }}", {{ hospital.score }} );
        createCircleProgressBar("#payment-{{ hospital.provider_id }}", {{ hospital.n_payment }} );
        createCircleProgressBar("#doctors-{{ hospital.provider_id }}", {{ hospital.n_md }} );
        createCircleProgressBar("#complications-{{ hospital.provider_id }}", {{ hospital.n_complications }} );
        createCircleProgressBar("#returns-{{ hospital.provider_id }}", {{ hospital.n_returns }} );
        createCircleProgressBar("#timely-{{ hospital.provider_id }}", {{ hospital.n_timely }} );
    {% endfor %}

    $("#loadingWrapper").hide();
    $("#hospitalsTableWrapper").show();
});
</script>
{% endblock %}